---
output:
  pdf_document: default
  html_document: default
---
# Load Libraries
```{r}
library(tidyverse)
library(RColorBrewer)
library(cowplot)
library(scales)
library(ggthemes)
```


# Load in the data
```{r}
data = read.csv(file ="https://raw.githubusercontent.com/BivinSadler/MSDS_6306_Doing-Data-Science/Master/Unit%2014%20and%2015%20Case%20Study%202/CaseStudy2-data.csv",
                         stringsAsFactors = T,
                         header = T)
```


# Look at the data
```{r}
str(data)
head(data)

##Looking for relationships, SCATTER PLOTS
data %>% ggplot(aes(x=Age, y=MonthlyIncome, color=Attrition)) +
  geom_point() + 
  geom_jitter() +
  scale_color_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  ggtitle("Attrition Rates - Monthly Income vs. Age") +
  scale_y_continuous(labels = scales::comma) +
  scale_y_continuous(labels=scales::dollar_format()) + 
  labs(y="Monthly Income") + 
  theme_economist() + 
  theme(legend.title = element_blank())

#TotalWorkingYears vs WorkLifeBalance, in regards to Attrition
data %>% ggplot(aes(x=TotalWorkingYears, y=WorkLifeBalance, color = Attrition)) + 
  geom_point() +
  geom_jitter() + 
  scale_color_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  ggtitle("Attrition Rates - PercentSalaryHike vs. YearsWithCurrManager")

#JobSatisfaction vs HourlyRate, in regards to Attrition
data %>% ggplot(aes(x=JobSatisfaction, y=HourlyRate, color=Attrition)) +
  geom_point() +
  geom_jitter() +
  geom_smooth() +
  scale_color_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  ggtitle("Attrition Rates - HourlyRate vs. JobSatisfaction")

#Age vs DailyRate, in regards to Attrition
data %>% ggplot(aes(x=Age, y=DailyRate, color=Attrition)) +
  geom_point() +
  geom_jitter() +
  geom_smooth() +
  scale_color_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  ggtitle("Attrition Rates - DailyRate vs. Age") + 
  theme_economist()

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

##Looking for relationships, BAR GRAPHS
data %>% ggplot(aes(x=Age, fill=Attrition)) +
  geom_bar() +
  scale_fill_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  ggtitle("Attrition Rates by Age") +
  scale_y_continuous(labels = scales::percent) + 
  labs(y="Attrition (%)")

#JobLevel vs MonthlyIncome
data %>% ggplot(aes(x=JobLevel, y=MonthlyIncome, color=JobLevel)) +
  geom_point() +
  geom_jitter() +
  ggtitle("Monthly Income vs. Job Level") +
  labs(y="Monthly Income", x="Job Level") +
  scale_y_continuous(labels = scales::comma)+
  scale_y_continuous(labels=scales::dollar_format()) +
  theme_economist() +
  theme(legend.position = "None", axis.title.y=element_text(vjust=1.8))


#DistanceFromHome in regards to Attrition
data %>% ggplot(aes(x=DistanceFromHome, fill=Attrition)) +
  geom_bar() +
  scale_fill_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  ggtitle("Attrition Rates by Distance From Home") +
  scale_y_continuous(labels = scales::percent) + 
  labs(y="Attrition (%)")

data %>% ggplot(aes(x=Age, fill=Attrition)) +
  geom_bar() +
  scale_fill_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  ggtitle("Attrition Rates by Age") +
  scale_y_continuous(labels = scales::percent) + 
  labs(y="Attrition (%)")  + 
  theme_economist() 

#MaritalStatus in regards to Attrition
data %>% ggplot(aes(x=MaritalStatus, fill=Attrition)) +
  geom_bar() +
  scale_fill_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  ggtitle("Attrition Rates by Marital Status") +
  scale_y_continuous(labels = scales::percent) + 
  labs(y="Attrition (%)") 

#Gender in regards to Attrition
data %>% ggplot(aes(x=Gender, fill=Attrition)) +
  geom_bar() +
  scale_fill_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  ggtitle("Attrition Rates by Gender") +
  scale_y_continuous(labels = scales::percent) + 
  labs(y="Attrition (%)")

#JobRole in regards to Attrition
data %>% ggplot(aes(x=JobRole, fill=Attrition)) +
  geom_bar() +
  theme(axis.text.x=element_text(angle=90)) +
  scale_fill_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  ggtitle("Attrition Rates by Job Role") +
  scale_y_continuous(labels = scales::percent) + 
  labs(y="Attrition (%)") +
  coord_flip() 

#Facet wrap of Age vs. MonthlyIncome, by Job Role
data %>% ggplot(aes(x=Age, y=MonthlyIncome, color=JobRole)) +
  geom_point() +
  geom_jitter() +
  geom_smooth(color = "black") +
  facet_wrap(~JobRole) + #facet wrap
  ggtitle("Monthly Income vs Age, by Job Role") +
  labs(y="Monthly Income") +
  scale_y_continuous(labels = scales::comma)+
  scale_y_continuous(labels=scales::dollar_format()) + 
  theme_economist() +
  theme(legend.position = "None", axis.title.y=element_text(vjust=1.8))

#YearsInCurrentRole in relation to Attrition
data %>% ggplot(aes(x=YearsInCurrentRole, fill=Attrition)) +
  geom_bar() +
  scale_fill_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  ggtitle("Attrition Rates by Years In Current Role") +
  scale_y_continuous(labels = scales::percent) + 
  labs(y="Attrition (%)")

#JobSatisfaction in relation to Attrition
data %>% ggplot(aes(x=JobSatisfaction, fill=Attrition)) +
  geom_bar() +
  scale_fill_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  ggtitle("Attrition Rates by Job Satisfaction") +
  scale_y_continuous(labels = scales::percent) + 
  labs(y="Attrition (%)")  + 
  theme_economist()

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

##Looking for relationships, BOXPLOTS
data %>% ggplot(aes(x=JobRole, y=MonthlyIncome, fill=JobRole)) +
  geom_boxplot() +
  ggtitle("Distibutions of Income by Job Role") +
  theme(axis.ticks.x = element_blank(),
        axis.text.x = element_blank()) + 
  scale_y_continuous(labels = scales::comma)+
  scale_y_continuous(labels=scales::dollar_format()) + 
  theme_economist()

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

##Looking for relationships, HISTOGRAMS

#Distribution of MonthlyIncome, by attrition - Histogram
data %>% ggplot(aes(x=MonthlyIncome, fill=Attrition)) + 
  geom_histogram() + 
  ggtitle("Distribution of Monthly Income & Resulting Attrition") +
  scale_fill_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  scale_y_continuous(labels = scales::percent) +
  scale_x_continuous(labels = scales::comma)+
  scale_x_continuous(labels=scales::dollar_format()) + 
  labs(y="Frequency") + 
  theme_economist()

#Distribution of MonthlyIncome, by attrition - Densiry plot
data %>% ggplot(aes(x=MonthlyIncome, fill=Attrition)) + 
  geom_density() + 
  ggtitle("Distribution of Monthly Income & Resulting Attrition") +
  scale_fill_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  scale_x_continuous(labels = scales::comma)+
  scale_x_continuous(labels=scales::dollar_format()) + 
  labs(y="Frequency") + 
  theme_economist() 

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 


```