# Load Libraries
```{r}
library(tidyverse)
library(RColorBrewer)
library(cowplot)
library(scales)
```


# Load in the data
```{r}
data = read.csv(file ="https://raw.githubusercontent.com/BivinSadler/MSDS_6306_Doing-Data-Science/Master/Unit%2014%20and%2015%20Case%20Study%202/CaseStudy2-data.csv",
                         stringsAsFactors = T,
                         header = T)
```


# Look at the data
```{r}
###The bar graph section has a couple of things that could be applied to each graph if we want, but I 
# am unsure how to get it working. For one, the graphs with percentages in terms of Attrition have 
# several trailing zeroes, and no decimals. The second thing that would probably be a good 
# quality of life fix would be to order whichever one we may want to use in descending order for a 
# better visual.


str(data)
head(data)

#Looking for relationships, SCATTER PLOTS
data %>% ggplot(aes(x=Age, y=MonthlyIncome, color=Attrition)) +
  geom_point() + 
  geom_jitter() +
  scale_color_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  ggtitle("Attrition Rates - MonthlyIncome vs. Age")

data %>% ggplot(aes(x=YearsWithCurrManager, y=PercentSalaryHike, color = Attrition)) + 
  geom_point() +
  geom_jitter() + 
  scale_color_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  ggtitle("Attrition Rates - PercentSalaryHike vs. YearsWithCurrManager")

data %>% ggplot(aes(x=JobSatisfaction, y=HourlyRate, color=Attrition)) +
  geom_point() +
  geom_jitter() +
  geom_smooth() +
  scale_color_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  ggtitle("Attrition Rates - HourlyRate vs. JobSatisfaction")

data %>% ggplot(aes(x=Age, y=DailyRate, color=Attrition)) +
  geom_point() +
  geom_jitter() +
  geom_smooth() +
  scale_color_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  ggtitle("Attrition Rates - DailyRate vs. Age")

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

#Looking for relationships, BAR GRAPHS
data %>% ggplot(aes(x=Age, fill=Attrition)) +
  geom_bar() +
  scale_fill_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  ggtitle("Attrition Rates by Age") +
  scale_y_continuous(labels = scales::percent) + 
  labs(y="Attrition (%)")

data %>% ggplot(aes(x=Education, fill=Attrition)) +
  geom_bar() +
  scale_fill_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  ggtitle("Attrition Rates by Education") +
  scale_y_continuous(labels = scales::percent) + 
  labs(y="Attrition (%)")

data %>% ggplot(aes(x=DistanceFromHome, fill=Attrition)) +
  geom_bar() +
  scale_fill_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  ggtitle("Attrition Rates by Distance From Home") +
  scale_y_continuous(labels = scales::percent) + 
  labs(y="Attrition (%)")

data %>% ggplot(aes(x=Age, fill=Attrition)) +
  geom_bar() +
  scale_fill_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  ggtitle("Attrition Rates by Age") +
  scale_y_continuous(labels = scales::percent) + 
  labs(y="Attrition (%)")

data %>% ggplot(aes(x=MaritalStatus, fill=Attrition)) +
  geom_bar() +
  scale_fill_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  ggtitle("Attrition Rates by Marital Status") +
  scale_y_continuous(labels = scales::percent) + 
  labs(y="Attrition (%)")

data %>% ggplot(aes(x=Gender, fill=Attrition)) +
  geom_bar() +
  scale_fill_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  ggtitle("Attrition Rates by Gender") +
  scale_y_continuous(labels = scales::percent) + 
  labs(y="Attrition (%)")

data %>% ggplot(aes(x=JobRole, fill=Attrition)) +
  geom_bar() +
  theme(axis.text.x=element_text(angle=90)) +
  scale_fill_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  ggtitle("Attrition Rates by Job Role") +
  scale_y_continuous(labels = scales::percent) + 
  labs(y="Attrition (%)") +
  coord_flip()

data %>% ggplot(aes(x=BusinessTravel, fill=Attrition)) +
  geom_bar() +
  facet_wrap(~JobSatisfaction) +  #facet wrap
  theme(axis.text.x=element_text(angle=90)) + 
  scale_fill_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  ggtitle("Attrition Rates by Business Travel Frequency & Job Satisfaction") +
  scale_y_continuous(labels = scales::percent) + 
  labs(y="Attrition (%)")

data %>% ggplot(aes(x=YearsInCurrentRole, fill=Attrition)) +
  geom_bar() +
  scale_fill_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  ggtitle("Attrition Rates by Years In Current Role") +
  scale_y_continuous(labels = scales::percent) + 
  labs(y="Attrition (%)")

###EXAMPLE OF TRAILING ZEROS ON Y AXIS, NO DECIMALS
data %>% ggplot(aes(x=JobSatisfaction, fill=Attrition)) +
  geom_bar() +
  scale_fill_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  ggtitle("Attrition Rates by Job Satisfaction") +
  scale_y_continuous(labels = scales::percent) + 
  labs(y="Attrition (%)")

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

#Looking for relationships, BOXPLOTS
data %>% ggplot(aes(x=JobRole, y=MonthlyIncome, fill=JobRole)) +
  geom_boxplot() +
  ggtitle("Distibutions of Income by Job Role") +
  theme(axis.ticks.x = element_blank(),
        axis.text.x = element_blank()) + 
  scale_y_continuous(labels = scales::comma)+
  scale_y_continuous(labels=scales::dollar_format())

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

#Looking for relationships, HISTOGRAMS. Can replace with logIncome if you want
data %>% ggplot(aes(x=MonthlyIncome, fill=Attrition)) + 
  geom_histogram() + 
  ggtitle("Distribution of Monthly Income & Resulting Attrition") +
  scale_fill_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  scale_y_continuous(labels = scales::percent) +
  scale_x_continuous(labels = scales::comma)+
  scale_x_continuous(labels=scales::dollar_format()) + 
  labs(y="Frequency")

data %>% ggplot(aes(x=MonthlyIncome, fill=Attrition)) + 
  geom_density() + 
  ggtitle("Distribution of Monthly Income & Resulting Attrition") +
  scale_fill_manual(values = c("Yes" = "#025e73", "No"="#f2916d")) +
  scale_x_continuous(labels = scales::comma)+
  scale_x_continuous(labels=scales::dollar_format()) + 
  labs(y="Frequency")

```